export const CATEGORYID_VERLOF = 1687;
export const CATEGORYID_GLIJTIJD = 8770;
export const CATEGORYID_RECUPERATIE = 8786;

export const ENTITLEMENTID_EXTRA_LEGAAL_VERLOF_Y1 = 1685;
export const ENTITLEMENTID_WETTELIJK_VERLOF = 1683;
export const ENTITLEMENTID_VERVANGENDE_FEESTDAGEN = 5987;
export const ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2022 = 8777;
export const ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2023 = 8773;
export const ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2024 = 8774;
export const ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2025 = 8775;
export const ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2026 = 8776;
export const ENTITLEMENTID_EXTRA_LEGAAL_VERLOF = 5989;
export const ENTITLEMENTID_EXTRA_LEGAAL_VERLOF_PC307 = 6885;
export const ENTITLEMENTID_KERST_NIEUW = 5985;
export const ENTITLEMENTID_ANCIENNITEIT = 5984;
export const ENTITLEMENTID_GLIJTIJD = 8770;
export const ENTITLEMENTID_RECUPERATIE = 8786;

export const ENTITLEMENTS_TO_TAKE = [
  ENTITLEMENTID_EXTRA_LEGAAL_VERLOF_Y1,
  ENTITLEMENTID_WETTELIJK_VERLOF,
  ENTITLEMENTID_VERVANGENDE_FEESTDAGEN,
  ENTITLEMENTID_HISTORISCHE_RECUPERATIE_2022,
  ENTITLEMENTID_RECUPERATIE,
  ENTITLEMENTID_GLIJTIJD,
];

export const TRANSFERABLE_ENTITLEMENTS = [
  ENTITLEMENTID_EXTRA_LEGAAL_VERLOF,
  ENTITLEMENTID_KERST_NIEUW,
  ENTITLEMENTID_ANCIENNITEIT,
  ENTITLEMENTID_EXTRA_LEGAAL_VERLOF_PC307,
];
